# Online Retail Market Basket Analysis
Below is a market basket analysis on a dataset from the UCI Machine Learning Repository. You can access the dataset using the following link. http://archive.ics.uci.edu/ml/datasets/Online+Retail

In [178]:
# import packages
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

In [179]:
# store data in df variable
df = pd.read_excel('Online Retail.xlsx')

In [180]:
# top 10 rows
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

In [181]:
# check for nulls
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [182]:
# drop rows where Description is null
df = df[df.Description != df.Description.isnull()]

# trim whitespace from Descriptions
df['Description'] = df['Description'].str.strip()

In [183]:
# countries for analysis
df.Country.unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [184]:
# USA purchases
df_US = (df[df['Country'] == 'USA'] 
          .groupby(['InvoiceNo', 'Description'])['Quantity'] 
          .sum().unstack().reset_index().fillna(0) 
          .set_index('InvoiceNo'))

# Canada purchases
df_Canada = (df[df['Country'] == 'Canada'] 
          .groupby(['InvoiceNo', 'Description'])['Quantity'] 
          .sum().unstack().reset_index().fillna(0) 
          .set_index('InvoiceNo'))

# Japan purchases
df_Japan = (df[df['Country'] == 'Japan'] 
          .groupby(['InvoiceNo', 'Description'])['Quantity'] 
          .sum().unstack().reset_index().fillna(0) 
          .set_index('InvoiceNo'))

# Italy purchases
df_Italy = (df[df['Country'] == 'Italy'] 
          .groupby(['InvoiceNo', 'Description'])['Quantity'] 
          .sum().unstack().reset_index().fillna(0) 
          .set_index('InvoiceNo'))

# Israel purchases
df_Israel = (df[df['Country'] == 'Israel'] 
          .groupby(['InvoiceNo', 'Description'])['Quantity'] 
          .sum().unstack().reset_index().fillna(0) 
          .set_index('InvoiceNo'))

In [185]:
# hot encode dataset
def hot_encode(x): 
    if(x<= 0): 
        return 0
    if(x>= 1): 
        return 1
    
df_US = df_US.applymap(hot_encode)
df_Canada = df_Canada.applymap(hot_encode)
df_Japan = df_Japan.applymap(hot_encode) 
df_Italy = df_Italy.applymap(hot_encode)
df_Israel = df_Israel.applymap(hot_encode)

#### US Market Basket

In [186]:
# US model
frq_items = apriori(df_US, min_support = 0.15, use_colnames = True)
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(CARD DOLLY GIRL),(TEA PARTY BIRTHDAY CARD),0.285714,0.285714,0.285714,1.0,3.5,0.204082,inf
1,(TEA PARTY BIRTHDAY CARD),(CARD DOLLY GIRL),0.285714,0.285714,0.285714,1.0,3.5,0.204082,inf
2,(EMBROIDERED RIBBON REEL SUSIE),(SET OF 12 FAIRY CAKE BAKING CASES),0.285714,0.285714,0.285714,1.0,3.5,0.204082,inf
3,(SET OF 12 FAIRY CAKE BAKING CASES),(EMBROIDERED RIBBON REEL SUSIE),0.285714,0.285714,0.285714,1.0,3.5,0.204082,inf
4,(SET OF 6 RIBBONS VINTAGE CHRISTMAS),(EMBROIDERED RIBBON REEL SUSIE),0.285714,0.285714,0.285714,1.0,3.5,0.204082,inf
5,(EMBROIDERED RIBBON REEL SUSIE),(SET OF 6 RIBBONS VINTAGE CHRISTMAS),0.285714,0.285714,0.285714,1.0,3.5,0.204082,inf
6,(SET/10 BLUE POLKADOT PARTY CANDLES),(EMBROIDERED RIBBON REEL SUSIE),0.285714,0.285714,0.285714,1.0,3.5,0.204082,inf
7,(EMBROIDERED RIBBON REEL SUSIE),(SET/10 BLUE POLKADOT PARTY CANDLES),0.285714,0.285714,0.285714,1.0,3.5,0.204082,inf
8,(EMBROIDERED RIBBON REEL SUSIE),(SET/10 IVORY POLKADOT PARTY CANDLES),0.285714,0.285714,0.285714,1.0,3.5,0.204082,inf
9,(SET/10 IVORY POLKADOT PARTY CANDLES),(EMBROIDERED RIBBON REEL SUSIE),0.285714,0.285714,0.285714,1.0,3.5,0.204082,inf

#### Canada Market Basket

In [187]:
# Canada model
frq_items = apriori(df_Japan, min_support = 0.1, use_colnames = True)
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
54,(PAPER BUNTING COLOURED LACE),(VICTORIAN SEWING BOX SMALL),0.107143,0.107143,0.107143,1.0,9.333333,0.095663,inf
55,(VICTORIAN SEWING BOX SMALL),(PAPER BUNTING COLOURED LACE),0.107143,0.107143,0.107143,1.0,9.333333,0.095663,inf
60,(RED RETROSPOT ROUND CAKE TINS),(RED RETROSPOT MINI CASES),0.107143,0.107143,0.107143,1.0,9.333333,0.095663,inf
61,(RED RETROSPOT MINI CASES),(RED RETROSPOT ROUND CAKE TINS),0.107143,0.107143,0.107143,1.0,9.333333,0.095663,inf
119,"(RED RETROSPOT ROUND CAKE TINS, BASKET OF TOAD...",(RED RETROSPOT MINI CASES),0.107143,0.107143,0.107143,1.0,9.333333,0.095663,inf
120,"(RED RETROSPOT MINI CASES, BASKET OF TOADSTOOLS)",(RED RETROSPOT ROUND CAKE TINS),0.107143,0.107143,0.107143,1.0,9.333333,0.095663,inf
121,(RED RETROSPOT ROUND CAKE TINS),"(RED RETROSPOT MINI CASES, BASKET OF TOADSTOOLS)",0.107143,0.107143,0.107143,1.0,9.333333,0.095663,inf
122,(RED RETROSPOT MINI CASES),"(RED RETROSPOT ROUND CAKE TINS, BASKET OF TOAD...",0.107143,0.107143,0.107143,1.0,9.333333,0.095663,inf
192,"(CHARLOTTE BAG DOLLY GIRL DESIGN, MINI WOODEN ...",(PARTY BUNTING),0.107143,0.107143,0.107143,1.0,9.333333,0.095663,inf
193,(PARTY BUNTING),"(CHARLOTTE BAG DOLLY GIRL DESIGN, MINI WOODEN ...",0.107143,0.107143,0.107143,1.0,9.333333,0.095663,inf

#### Japan Market Basket

In [188]:
# Japan model
frq_items = apriori(df_Japan, min_support = 0.13, use_colnames = True)
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
2,"(SET 3 RETROSPOT TEA,COFFEE,SUGAR)",(BASKET OF TOADSTOOLS),0.142857,0.142857,0.142857,1.0,7.0,0.122449,inf
3,(BASKET OF TOADSTOOLS),"(SET 3 RETROSPOT TEA,COFFEE,SUGAR)",0.142857,0.142857,0.142857,1.0,7.0,0.122449,inf
4,(CHARLOTTE BAG DOLLY GIRL DESIGN),(LUNCH BAG DOLLY GIRL DESIGN),0.142857,0.142857,0.142857,1.0,7.0,0.122449,inf
5,(LUNCH BAG DOLLY GIRL DESIGN),(CHARLOTTE BAG DOLLY GIRL DESIGN),0.142857,0.142857,0.142857,1.0,7.0,0.122449,inf
12,(SET OF 72 RETROSPOT PAPER DOILIES),(SET OF 72 PINK HEART PAPER DOILIES),0.142857,0.142857,0.142857,1.0,7.0,0.122449,inf
13,(SET OF 72 PINK HEART PAPER DOILIES),(SET OF 72 RETROSPOT PAPER DOILIES),0.142857,0.142857,0.142857,1.0,7.0,0.122449,inf
14,"(SET 3 RETROSPOT TEA,COFFEE,SUGAR, RED SPOTTY ...",(BASKET OF TOADSTOOLS),0.142857,0.142857,0.142857,1.0,7.0,0.122449,inf
16,"(RED SPOTTY BISCUIT TIN, BASKET OF TOADSTOOLS)","(SET 3 RETROSPOT TEA,COFFEE,SUGAR)",0.142857,0.142857,0.142857,1.0,7.0,0.122449,inf
17,"(SET 3 RETROSPOT TEA,COFFEE,SUGAR)","(RED SPOTTY BISCUIT TIN, BASKET OF TOADSTOOLS)",0.142857,0.142857,0.142857,1.0,7.0,0.122449,inf
19,(BASKET OF TOADSTOOLS),"(SET 3 RETROSPOT TEA,COFFEE,SUGAR, RED SPOTTY ...",0.142857,0.142857,0.142857,1.0,7.0,0.122449,inf

#### Italy Market Basket

In [189]:
# Italy model
frq_items = apriori(df_Italy, min_support = 0.04, use_colnames = True)
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
184,(RED RETROSPOT CHARLOTTE BAG),(WOODLAND CHARLOTTE BAG),0.054545,0.054545,0.054545,1.0,18.333333,0.05157,inf
185,(WOODLAND CHARLOTTE BAG),(RED RETROSPOT CHARLOTTE BAG),0.054545,0.054545,0.054545,1.0,18.333333,0.05157,inf
221,"(RED RETROSPOT CHARLOTTE BAG, ABC TREASURE BOO...",(WOODLAND CHARLOTTE BAG),0.054545,0.054545,0.054545,1.0,18.333333,0.05157,inf
222,"(WOODLAND CHARLOTTE BAG, ABC TREASURE BOOK BOX)",(RED RETROSPOT CHARLOTTE BAG),0.054545,0.054545,0.054545,1.0,18.333333,0.05157,inf
223,(RED RETROSPOT CHARLOTTE BAG),"(WOODLAND CHARLOTTE BAG, ABC TREASURE BOOK BOX)",0.054545,0.054545,0.054545,1.0,18.333333,0.05157,inf
224,(WOODLAND CHARLOTTE BAG),"(RED RETROSPOT CHARLOTTE BAG, ABC TREASURE BOO...",0.054545,0.054545,0.054545,1.0,18.333333,0.05157,inf
292,"(CHILDRENS APRON APPLES DESIGN, JUMBO BAG WOOD...",(JUMBO BAG TOYS),0.054545,0.054545,0.054545,1.0,18.333333,0.05157,inf
297,(JUMBO BAG TOYS),"(CHILDRENS APRON APPLES DESIGN, JUMBO BAG WOOD...",0.054545,0.054545,0.054545,1.0,18.333333,0.05157,inf
298,"(RECYCLING BAG RETROSPOT, CHILDRENS APRON APPL...",(JUMBO BAG TOYS),0.054545,0.054545,0.054545,1.0,18.333333,0.05157,inf
303,(JUMBO BAG TOYS),"(RECYCLING BAG RETROSPOT, CHILDRENS APRON APPL...",0.054545,0.054545,0.054545,1.0,18.333333,0.05157,inf

#### Israel Market Basket

In [190]:
# Israel model
frq_items = apriori(df_Israel, min_support = 0.12, use_colnames = True)
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])
rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(CHARLOTTE BAG DOLLY GIRL DESIGN),(BLUE DINER WALL CLOCK),0.222222,0.222222,0.222222,1.0,4.5,0.17284,inf
1,(BLUE DINER WALL CLOCK),(CHARLOTTE BAG DOLLY GIRL DESIGN),0.222222,0.222222,0.222222,1.0,4.5,0.17284,inf
10,(FRYING PAN BLUE POLKADOT),(BLUE POLKADOT GARDEN PARASOL),0.222222,0.222222,0.222222,1.0,4.5,0.17284,inf
11,(BLUE POLKADOT GARDEN PARASOL),(FRYING PAN BLUE POLKADOT),0.222222,0.222222,0.222222,1.0,4.5,0.17284,inf
12,(BLUE POLKADOT GARDEN PARASOL),(FRYING PAN PINK POLKADOT),0.222222,0.222222,0.222222,1.0,4.5,0.17284,inf
13,(FRYING PAN PINK POLKADOT),(BLUE POLKADOT GARDEN PARASOL),0.222222,0.222222,0.222222,1.0,4.5,0.17284,inf
14,(BLUE POLKADOT GARDEN PARASOL),(MILK PAN BLUE POLKADOT),0.222222,0.222222,0.222222,1.0,4.5,0.17284,inf
15,(MILK PAN BLUE POLKADOT),(BLUE POLKADOT GARDEN PARASOL),0.222222,0.222222,0.222222,1.0,4.5,0.17284,inf
16,(BLUE POLKADOT GARDEN PARASOL),(MILK PAN RED RETROSPOT),0.222222,0.222222,0.222222,1.0,4.5,0.17284,inf
17,(MILK PAN RED RETROSPOT),(BLUE POLKADOT GARDEN PARASOL),0.222222,0.222222,0.222222,1.0,4.5,0.17284,inf